language: c

services:
  - docker

notification:
  email:
    recipients:
      - tomasforne1@gmail.com
      - tomas.forne-cappeau@epitech.eu
      - paul.tardivel@epitech.eu
    on_success: never
    on_failure: always

before_install:
  - docker pull epitechcontent/epitest-docker

jobs:
  include:
    - stage: Build
      name: "Building"
      script: docker run -v "$PWD:/app" epitechcontent/epitest-docker bash -c "cd /app && make"
      after_script: docker stop epitechcontent/epitest-docker
    - stage: Tests
      name: "Basic Tests"
      script: docker run -v "$PWD:/app" epitechcontent/epitest-docker bash -c "cd /app && ./basic_tests.sh navy"
      after_script: docker stop epitechcontent/epitest-docker
      - script: docker run -v "$PWD:/app" epitechcontent/epitest-docker bash -c "cd /app && make tests_run"
      name: "Make the tests"
      after_script: docker stop epitechcontent/epitest-docker
    - stage: Deployment
      name: "Push to blih repo"
      script: docker run -v "$PWD:/app" epitechcontent/epitest-docker bash -c "cd /app && ./deploy.sh"
      after_script: docker stop epitechcontent/epitest-docker

stages:
  - Build
  - Tests
  - name: Deployment
    if: branch = master
