language: c

services:
  - docker

notifications:
  email:
    recipients:
      - tomas.forne-cappeau@epitech.eu
      - paul.tardivel@epitech.eu
    on_success: never
    on_failure: always

env:
  global:
    - DOCKER_REPO=epitechcontent/epitest-docker:latest
    - CODECOV_TOKEN=66b9dce5-a64e-48eb-a8a4-6f10a4ad1d2d

install:
  - docker pull ${DOCKER_REPO}

jobs:
  include:
    - stage: Build
      name: "Building"
      script: docker run -v "$PWD:/app" ${DOCKER_REPO} bash -c "cd /app && make"
    - stage: Tests
      name: "Basic Tests"
      script: docker run -v "$PWD:/app" ${DOCKER_REPO} bash -c "cd /app && ./tests/basic_tests.sh navy"
      after_success:
        - bash <(curl -s https://codecov.io/bash)
        - coveralls --exclude lib --exclude tests --gcov-options
    - script: docker run -v "$PWD:/app" ${DOCKER_REPO} bash -c "cd /app && make tests_run"
      name: "Make the tests"
    - stage: Deployment
      name: "Push to blih repo"
      script:
        - ssh-keyscan -H git.epitech.eu >> ~/.ssh/known_hosts
        - git remote add blih git@git.epitech.eu:/paul.tardivel@epitech.eu/PSU_navy_2018
        - git fetch --all

stages:
  - Build
  - Tests
  - name: Deployment
    if: branch = deploy