language: c

services: docker

notification:
  email:
    recipients:
      - tomas.forne-cappeau@epitech.eu
      - paul.tardivel@epitech.eu
      - tomasforne1@gmail.com
    on_success: never
    on_failure: always

jobs:
  include:
    - stage: "Build"
      name: "Building"
      script: make
    - stage: "Tests"
      name: "Basic Tests"
      script: ./basic_tests.sh navy

deploy:
  provider: script
  script: ./deploy.sh
  on:
    branch: master
