language: c

services:
  - docker

notification:
  email:
    recipients:
      - tomasforne1@gmail.com
      - tomas.forne-cappeau@epitech.eu
      - paul.tardivel@epitech.eu
    on_success: always
    on_failure: always

before_install:
  - docker pull epitechcontent/epitest-docker

jobs:
  include:
    - stage: "Build"
      name: "Building"
      script: docker run -v "$PWD:/app" epitechcontent/epitest-docker bash -c "cd /app && make"
      after_script: docker stop epitechcontent/epitest-docker
    - stage: "Tests"
      name: "Basic Tests"
      script: docker run -v "$PWD:/app" epitechcontent/epitest-docker bash -c "cd /app && ./basic_tests.sh navy"
      after_script: docker stop epitechcontent/epitest-docker


deploy:
  provider: script
  script: docker run -c "$PWD:/app" epitechcontent/epitest-docker bash -c "cd /app && ./deploy.sh"
  after_script: docker stop epitechcontent/epitest-docker
  on:
    branch: master
